services:
  - type: web
    name: ecommerce-mern
    env: node
    buildCommand: |
      cd ecommerce/client && npm install && npm run build
      cd ../server && npm install
    startCommand: node ecommerce/server/server.js
    staticDir: Ecommerce/client/dist